apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: my-nginx
---
# https
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: nginx-ingressroute-https
#  namespace: default
#spec:
#  entryPoints:
#    - websecure
#  routes:
#  - match: Host(`n.ngames-dev.cn`) && PathPrefix(`/`)
#    kind: Rule
#    services:
#    - name: my-nginx
#      port: 80
#  tls:
#    secretName: ali-tls
---
# redirect-https
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: redirect-https
#spec:
#  redirectScheme:
#    scheme: https
---
# http
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`n.ngames-dev.cn`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: my-nginx
      port: 80
    #middlewares: 
    #- name: redirect-https